webtorrent/node-bencode

.travis.yml
Due to devDependencies utilizing the `^` version operator in their dependencies,
and node 0.8's version of npm being incompatible with it, the travis builds fail.
Also, I think we can stop consciously supporting node v0.8 now.
=> Remove node v0.8 from .travis.yml

lib/encode.js
@jhermsmeier @themasch 
Convert boolean values to 0/1. 
I wasn't sure if this was "proper" behavior and something that should be included since booleans are not really supported. It helped in my case since I didn't want to have to convert all boolean values before sending the bencode message. I think at the very least there should be some error handling for this case.
=> Handle boolean case

README.md, benchmark/encoding-length.js, bencode.js, lib/decode.js, lib/encode.js, test/abstract-encoding.test.js
See #37 and https://github.com/mafintosh/abstract-encoding
Implements the following API in a backwards-compatible fashion (meaning: no major version bump necessary):
```
byteCount = bencode.encodingLength(value)
buffer = bencode.encode(value, [buffer], [offset])
value = bencode.decode(buffer, [start], [end], [encoding])
```
**TODO:**
**NOTE:** It has a minor effect on performance (aournd 500-1000 op/s on my machine)
=> Implement the `abstract-encoding` API

README.md
A `s` was missing in the example string to be decoded :)
=> Fix string to be decoded in README

test/BEP-0023.test.js, test/data/announce-compacted-peers.bin
Add tests for correct handling of compact peer lists, as defined in [[BEP 0023]](http://www.bittorrent.org/beps/bep_0023.html)
Ref #54
=> Test correct handling of compacted peer lists [BEP 0023]

README.md, package.json
Since Testling has been non-functional for more than 2 years now, this can be removed for now, and maybe added back when Testling works again. If at all – who knows how likely that is.
=> Remove Testling CI badge & package.json info

.travis.yml
I think we can now safely get rid of the `0.x` versions,
as those have been deprecated a wee while ago.
=> Update tested node versions on Travis CI

lib/decode.js, lib/encode.js, test/null-values.test.js
**Description**
Currently, when encoding objects of any kind, values that are either `null` or `undefined` will throw `TypeError: Cannot read property 'constructor' of null` because we don't even check for those.
As it can become very cumbersome to remove any keys (or items) with null-values when working with more complex data structures, I propose ignoring null-values during encoding, so that they'll be left out in the encoded data.
This change should theoretically be backwards compatible, if I haven't missed anything.
**Changes**
- `bencode.decode()` now returns `null` if fed with empty values (`''` or `new Buffer(0)`)
- `bencode.encode()` and parts now skip / ignore `null` and `undefined` in Arrays and Objects
- `bencode.encode()` now returns an empty Buffer / String when invoked on …
=> Ignore null-values when encoding

package.json, test/mocha.opts
- Adds `npm run style` to auto-fix code style and improve laziness efficiency
- Remove `mocha.opts`, which hasn't been in use for ages
=> Remove unused mocha.opts, add script to standard --fix

README.md, lib/encode.js, test/BEP-0023.test.js, test/abstract-encoding.test.js, test/data.js, test/decode.buffer.test.js, test/encode.test.js, test/null-values.test.js
...with `Buffer.from()` & `Buffer.allocUnsafe()`
=> replace deprecated `new Buffer()`

.travis.yml, lib/encode.js, package.json, test/BEP-0023.test.js, test/abstract-encoding.test.js, test/data.js, test/decode.buffer.test.js, test/encode.test.js, test/null-values.test.js
We support these node versions in `bittorrent-dht` and they lack the
new Buffer.from, etc. methods.
`safe-buffer` provides a buffer with the new methods, or does nothing
if the node version is new enough.
=> Support Node 0.10, 0.12, and early Node 4

.travis.yml
BREAKING CHANGE: This drops support Node v0.10.x, and v0.12.x
while adding Node v8.x.x, as v9.x.x is now stable.
=> test(ci): Drop Node v0.10.x & v0.12.x, add 8.x.x

lib/encode.js, test/encode.test.js
**Changes:**
Adds a check for typed Arrays by utilizing `ArrayBuffer.isView()`, which seems to be the safest & fastest way to check for that (?), and also considers DataViews.
Also adds checks for Numbers & Booleans constructed via `new Number(x)` and `new Boolean(x)`, which ideally shouldn't be done anywhere, but it wouldn't hurt to handle those correctly as well.
Typed arrays are now encoded raw as buffers (not as dictionaries or lists), meaning that for example, a Float32Array will be encoded as a Buffer which the floats can be read back from with `buffer.readFloat32LE()`, as demonstrated below:
```js
> var data = new Float32Array([ 1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9, 9.0 ])
> var b = Buffer.from(data.buffer)
> b
<Buffer 9a 99 99 3f 33 33 13 40 9a 99 59 40 00 00 90 40 33 33 b3 40 …
```
=> Improve encoding type checks

lib/encode.js, test/encode.test.js
This is a followup to #64 that fixes support for `ArrayBufferView` that doesn't use the whole underlying `ArrayBuffer`
=> Fix support for any valid `ArrayDataView`

lib/decode.js, lib/encode.js
There were still two instances of calling `new Buffer()`, which this updates to use `Buffer.from()`, while also adding use of `safe-buffer` in `lib/decode.js`
=> Fix deprecation warning on Buffer() constructor

package.json, test/encode.test.js
- standard 9.0.2 -> 12.0.1
- tap-spec 4.1.0 -> 5.0.0
**Depends on** #83 to avoid Buffer deprecation warning errors from `standard`
=> Update dev dependencies

lib/encode.js, test/encode.test.js
This adds support for encoding `Map`s and `Set` through `bencode.encode()`
=> Add support for encoding Maps and Sets

.travis.yml
As noted on #89, this drops CI tests for Node versions 6 and 8, while adding versions 10 and 12 to the matrix
=> Update node versions, drop v4/v6, add v10/v12

lib/encode.js, lib/encoding-length.js, lib/index.js, lib/util.js, test/encoding-length.test.js
This adds a standalone implementation for `.encodingLength(value)`,
which is significantly faster than encoding & getting the length from
the returned buffer.
This will also enable us to pre-allocate a correctly sized buffer when
encoding, potentially enabling performance improvements, as we can avoid
allocating a large amount of small buffers followed by concatenation,
and instead write directly into the pre-allocated buffer.
Further, `.encodingLength()` supports new types for lists and
dictionaries; namely `Set`s and `Map`s
=> Add dedicated bencode.encodingLength() implementation

lib/decode.js, lib/encode.js, lib/encoding-length.js, lib/index.js, package-lock.json, package.json, test/BEP-0023.test.js, test/abstract-encoding.test.js, test/data.js, test/decode.buffer.test.js, test/decode.utf8.test.js, test/encode.test.js, test/encoding-length.test.js, test/null-values.test.js
part of https://github.com/brave/brave-browser/issues/5490
(Always require latest Buffer module)
=> rm safe-buffer

CHANGELOG.md, CONTRIBUTORS, package.json
safe-buffer is not required anymore since node v6 added the methods to the core.
Thanks to @jimmywarting for this patch!
=> fix: Patch release to drop a dependecy to safe-buffer
